### ISSUE TITLE
Call out C# 7 explicitly

### ISSUE THREAD

**Issue by juliahayward** [red-gate/Tech-Radar#101]
Should we be explicitly adopting C# 7 as standard across the organisation, in parallel with keeping projects up to date on framework versions?

**Comment by nyctef** [comment]
👍 I think we generally want to use the latest version of C# possible at all times (afaik usually the only blocker is getting the build agents set up with new VS/MSBuild versions)

**Comment by fffej** [comment]
I agree - I think the difficulty comes when [C# 8](https://blogs.msdn.microsoft.com/dotnet/2018/11/12/building-c-8-0/) comes out and we have to migrate to .NET Core 3.
