### ISSUE TITLE
[Techniques] Dogfooding

### ISSUE THREAD

**Issue by juliahayward** [red-gate/Tech-Radar#102]
Do we or Core do any? We really should.

**Comment by garethbragg** [comment]
This came up a little in the discussion around #35.

**Comment by garethbragg** [comment]
For context,  Ithink the current state is:

* We don't (actively) dogfood anything
* We generally agree we should
* "Versioning Teams to investigate this by looking at how CORE manage databases."

I don't know if any other tools are used internally.

**Comment by fffej** [comment]
I've put dogfooding in "Adopt".

I intend this to mean that when we're looking at a technology and we've got a choice we should prefer our own by default (and the Tech Radar should be the way of indicating deviations from this).
