### ISSUE TITLE
[Techniques] Unit Tests / Test-Driven Development

### ISSUE THREAD

**Issue by fffej** [red-gate/Tech-Radar#110]
I think we'd all unanimously agree (🤞) that unit tests are a good thing, so I'd like to suggest they should be in Adopt.

Where does TDD fit in? Are any teams in a position to experiment with doing that for a significant period of time and reporting on how it goes?

**Comment by nyctef** [comment]
Just "TDD" by itself seems pretty broad - might be useful to break it up into more specific techniques that we can tackle separately?

eg here's a random list:

- test-first: discipline to always write a failing test before getting into coding the solution
- always make sure a you see a test go red (and for the right reason): I've been bitten by this one more often that I'll admit >.>
- [discovery testing](https://github.com/testdouble/contributing-tests/wiki/Discovery-Testing): how to build an entire application top-down with TDD
- [detroit-school TDD](https://github.com/testdouble/contributing-tests/wiki/Detroit-school-TDD): red/green/refactor, minimal change to make test pass, striving for realism
- TDD everywhere: is it possible to use TDD for everything? What points do we say we're allowed to not TDD things? (eg UI style changes, third-party adapter classes, etc?)
- making tests [as fast as possible](https://github.com/testdouble/contributing-tests/wiki/Feedback-Loop)
- (and everything else in this wiki: https://github.com/testdouble/contributing-tests/wiki)
- Test-driven design: learning how to "listen to the tests"
- probably a whole bunch of other things not in this list

**Comment by angellaa** [comment]
I agree to have unit testing in the ADOPT. 

I don't think getting more specific on the TDD approach help for the radar. When you do TDD you can use either the classic approach or the London style TDD or any other inn the same application so I am ok to keep TDD as a broad concept. 

I would be happy to experiment using TDD in my team if there is enough interest from my peers.

**Comment by nyctef** [comment]
I guess the question for me is what exactly it means to be "using TDD." I use a lot of the techniques from that list a lot of the time, but I don't know if I should claim I'm already doing TDD, because I'm not particularly consistent or disciplined about it.

**Comment by fffej** [comment]
I'm going to close this issue out because our [CSharpCodingGuidelines](https://github.com/red-gate/CSharpGuidelines/) are going to cover this in much more detail.
