### ISSUE TITLE
[Tools] R# dictionary/spellchecker + American spelling

### ISSUE THREAD

**Issue by Greg-Smulko** [red-gate/Tech-Radar#111]
See https://www.jetbrains.com/help/resharper/Spell_Checking.html for more info.

We use it in versioning with our team-shared dictionary, see https://github.com/red-gate/readyroll/blob/4c046692ace2ecd0b3da8513451cf38f19b932e8/SqlChangeAutomation.sln.DotSettings#L374

It allows to spot spelling mistakes earlier, which results in overall better quality of the code.

Maybe it should be a separate issue actually, but I'd propose to codify usage of American English in code for the below reasons:
- for consistency, as .NET itself has American spelling, as well as most other libraries
- [Honeycomb writing guide](http://honeycomb.red-gate.com/writing-guide/usage-dictionary):
> We use American English because it’s the form most of our users are familiar with. The exceptions are job ads and marketing material like flyers aimed at the UK market.

**Comment by nyctef** [comment]
http://honeycomb.red-gate.com/writing-guide/applications (as well as previous RG style guides) has this:

> Use American English, unless you’re writing exclusively for the British market

which in the past I've taken to mean that we write code in BrE. I don't have any particular attachment to that, though - I'd totally be up for switching to AmE everywhere just to simplify things :)

**Comment by fffej** [comment]
👍 to this from me. Consistency is more important than spelling colour right 😄
