### ISSUE TITLE
[Techniques] Concierge customers

### ISSUE THREAD

**Issue by Greg-Smulko** [red-gate/Tech-Radar#112]
Try to find concierge customers for new features to shorten the feedback loop.

**Comment by garethbragg** [comment]
I think there's something interesting about techniques for delivering software, which may relate to this?

* Do we encourage frequent update & slow-moving release channels?
* Do we encourage private builds?
* Do we encourage beta/EAP programmes?
* Is there something about "major" releases that relates to this?
