### ISSUE TITLE
[Techniques] Dedicated tech-debt time

### ISSUE THREAD

**Issue by Greg-Smulko** [red-gate/Tech-Radar#113]
Experiment with different techniques of paying the technical debt. 

For instance 
- the Kaizen Rota in SQL Monitor teams: "1 person per team, every week".

**Comment by fffej** [comment]
See [preview](https://radar.thoughtworks.com/?sheetId=https%3A%2F%2Fraw.githubusercontent.com%2Fred-gate%2FTech-Radar%2F6234c95c2c8ba1452dd8f66c87fbe0da99c637a0%2Fradar.csv)

**Comment by fffej** [comment]
Great spot - it's good to capture things that we're already doing. I created a #119 and I've asked someone from the Monitor teams to review.

**Comment by allymparker** [comment]
That's not what just what we're trying to achieve in the Monitor teams with the Kaizen rota - it's more about working on the continuous improvement that allows us to work towards our technical vision.  

For instance, as well as "paying technical debt" in the form of removing legacy tech, we've been working on getting better long range error detection with Raygun, Improving our dashboards so we can have better FUR etc.  

It'd be nice to reword this away from Tech Debt and more towards Kaizen/Continuous Improvement.

**Comment by fffej** [comment]
@allymparker Could you reword the PR accordingly? (or just nuke it and create another).
