### ISSUE TITLE
[Techniques] - Tests Refactoring

### ISSUE THREAD

**Issue by angellaa** [red-gate/Tech-Radar#114]
Writing tests is important but not enough. Tests should also be easy to understand and maintain.

Test code needs to be treated as production code and for that reason test refactoring is an important technique to adopt.

I think this should be in ADOPT.

I noticed we don't have an entry for just "Refactoring" so maybe we can add that separately or merge the two together?

**Comment by garethbragg** [comment]
Considering much of my time on SoC was spent doing this, I strongly agree 😃

**Comment by fffej** [comment]
@angellaa Do you want to create a PR for this?

I think all we need to say is that we treat test code just as we would production code (normal guidelines apply).

**Comment by garethbragg** [comment]
Is this more suited to the [CSharpGuidelines](https://github.com/red-gate/CSharpGuidelines) than the Tech radar?

**Comment by fffej** [comment]
Good point @garethbragg - let's move this over .

**Comment by garethbragg** [comment]
I've created a CSharpGuidelines issue for this, so will close this one down.
