### ISSUE TITLE
[Tools] Opinionated code formatters

### ISSUE THREAD

**Issue by nyctef** [red-gate/Tech-Radar#116]
Related to https://github.com/red-gate/Tech-Radar/issues/109 

On Figleaf, we use [prettier](https://github.com/prettier/prettier), along with vscode's prettier extension and `"editor.formatOnSave": true` to solve almost all of our code style problems for the frontend (we use tslint to solve the rest :)

The difference between prettier and most code formatters is that prettier discards (almost) all of the existing code formatting, so that the code ends up being formatted exactly the same way regardless of who wrote it. Prettier also has very few formatting options, so we didn't argue for long about how to configure it! This is awesome and I wish more tools like this were available - I've looked for something similar for C# and haven't been able to find anything yet.

**Comment by garethbragg** [comment]
I hadn't heard of prettier before. Sounds interesting.

Sounds like you're exploring it at the moment?

**Comment by adrianbanks** [comment]
We also use prettier in HammerHeads for our Javascript.

**Comment by nyctef** [comment]
> Sounds like you're exploring it at the moment?

We've been using it for about a year and haven't hit any issues as far as I know, so it could potentially go in Adopt

**Comment by fffej** [comment]
👍 from me for Adopt: Prettier. @adrianbanks or @nyctef - fancy creating a PR?

**Comment by smobs** [comment]
I would consider including "Hand formatted TS/JS" in endure/retire.

**Comment by nyctef** [comment]
> I would consider including "Hand formatted TS/JS" in endure/retire.

👍 I agree we should retire hand-formatting code where possible - do we have anyone doing this? Does this need to be on the radar, or is "adopt formatters" enough?
