### ISSUE TITLE
[Techniques] master is always releasable

### ISSUE THREAD

**Issue by nyctef** [red-gate/Tech-Radar#117]
This is based on #108 ("Stop the line when a build is red")

Saying that master is always releasable imposes an additional constraint: when master is green, master can be released to users. This requires a high degree of confidence in automated tests (high coverage of code/behaviours and likely some [installer tests](https://github.com/red-gate/Tech-Radar/issues/106)) and in the quality of the product itself (any work that isn't fit to release to everyone yet will need to be [hidden behind feature flags](https://github.com/red-gate/Tech-Radar/issues/104))

**Comment by garethbragg** [comment]
Strongly supportive of this.

I've been trying to understand for a long while how far Redgate is from the reality of "master is always releasable".

(Release testing should definitely be in retire, if anyone still does it. We're better than that.)

**Comment by nyctef** [comment]
there's probably some kind of maturity model here:

1. master is never releasable. We don't trust the product to not be broken at any given time, so we do a comprehensive release test of the whole product each time we release. We release once a year or so.
2. master is sometimes releasable. We'll do a significant bit of work, and then go through a period of stabilization and bugfixes after which we're confident that the product can be released. We release every few months or so.
3. master is usually releasable. We're generally confident in the product and the automated tests surrounding it, but from time to time we might know about an issue which is preventing the product from being released. We might do some quick non-comprehensive manual testing before a release just to double-check that the product is good to go. We commit to trying to release on a regular basis, usually weekly.
4. master is always releasable. We have enough confidence in the product and automated tests around it that anyone can press the release button at any time. We release whenever we have something to release.

I think we're generally around 3 - I want to claim Figleaf is at 4, although I don't know if that's just because something hasn't gone horribly wrong yet :)

**Comment by smobs** [comment]
I see "master as always releasable" as an ethos a team will adopt and then constantly strive to make true.
We should act like master is always releasable at any time, and when we discover that it isn't/wasn't releasable, reflect on why and add the appropriate checks for next time.

**Comment by fffej** [comment]
@nyctef Do you fancy making a PR to add this to adopt? Toby's wording is great - this is what we aspire to adopt. It's OK if teams do release testing, but it should not be done by default and doing it should prompt some soul-searching about why we don't have the confidence.
