### ISSUE TITLE
[Techniques] #nobugs

### ISSUE THREAD

**Issue by nyctef** [red-gate/Tech-Radar#118]
Disclaimer: this is just something I heard about at Prognet :)

Basically this means:
- turning "discovering a bug" into a [stop-the-line](https://github.com/red-gate/Tech-Radar/issues/108) event
- not keeping any kind of bug backlog

**Comment by fffej** [comment]
@joselima will probably be able to help with this one?

**Comment by garethbragg** [comment]
I've been an advocate of a zero bug policy for a while, and would be keen to see team/s actively explore using it.

**Comment by ChrisHurley** [comment]
I wouldn't say we're quite as far as a full implementation of #nobugs but I do generally agree with the principle, and on our team we try to address most issues we discover as we find them rather than having a large bug backlog.

**Comment by joselima** [comment]
Assuming you mean a zero-bug policy, whilst I have no first hand experience on implementing it, I have had quite a few conversations this year on this topic. More specifically with Prompt, and I know it's something we are keen to experiment with, so like @garethbragg said I'd also be keen to see teams trying it out and writing about their experiences.

Here are some of the articles I've read in the past about the topic:
- https://medium.com/qualityfaster/the-zero-bug-policy-b0bd987be684
- https://medium.com/swlh/how-we-got-to-zero-bugs-and-implemented-a-zero-bug-policy-c77ee3f2e50b

**Comment by garethbragg** [comment]
I've some experience working with a ZBP, and would be happy to support people in trying it out.

**Comment by fffej** [comment]
I think all we need here is a team committed to exploring it for long enough to reach a position (sounds like both @garethbragg and @joselima would be keen to support).

@red-gate/producttechleads Anyone wanting to volunteer?

**Comment by ChrisHurley** [comment]
I feel like we're not too far off this - it might be interesting to see what more we'd have to do to be following it officially?

**Comment by fffej** [comment]
@ChrisHurley Would you be happy to give it a try at some point over the next six months and commit to exploring it?

**Comment by ChrisHurley** [comment]
If @garethbragg could give us some guidance on what we'd need to do to be doing it officially, sure!

**Comment by chrisgeorge0911** [comment]
The manner in which most of our teams operate now, a zero-bug policy is a very realistic thing to achieve... certainly in favour of this.
