### ISSUE TITLE
[Tools] IRedgateSerializable

### ISSUE THREAD

**Issue by PeterGerrard** [red-gate/Tech-Radar#122]
This is part of our legacy tooling, as such we should add it to Retire

**Comment by fffej** [comment]
Should we? 

`IRedgateSerializable` is yucky (it's a home brew framework for serialization) but removing it from existing products has significant cost. We'd have to make sure we can read in all old versions of whatever is serialized, perform upgrade logic and replace with something better. It's unclear to me whether that's worth the benefit of the cost.

I'd vote Endure for this one.

**Comment by PeterGerrard** [comment]
I was tossing up on this between Endure and Retire. Was as much wanting to hear other people's thoughts

**Comment by garethbragg** [comment]
Is this true of all the `RedGate.Legacy.*` packages?

**Comment by PeterGerrard** [comment]
Seems fair, I'll add a PR
