### ISSUE TITLE
[Language] PowerShell

### ISSUE THREAD

**Issue by PeterGerrard** [red-gate/Tech-Radar#124]
We use PowerShell extensively for scripting so we should mark it as adopt. We also use it as the basis of SQL Change Automation's automated components and some of its plugins.

We might want to consider which versions of PowerShell to support/recommend:

I would suggest:
PowerShell 3 Endure
PowerShell 5/6 Adopt

**Comment by nyctef** [comment]
Related: #33 

I take it SCA requires Powershell 3 or higher? Is the same true for Clone's cmdlets as well?

**Comment by PeterGerrard** [comment]
SCA is definitely 3 or higher (which has caused some issues) I assume Clone is the same

**Comment by mark-raymond** [comment]
SQL Clone's cmdlets installer says it requires PowerShell 3+.

**Comment by fffej** [comment]
I think we're close to agreement here.

@PeterGerrard could you create a PR and we'll see if we get agreement on it? 😄

**Comment by ChrisHurley** [comment]
Just to check here, we're saying that any new suites of PowerShell cmdlets we build for customer consumption should require PowerShell 5/6 (shouldn't start something new based on something in Endure)?

**Comment by mark-raymond** [comment]
So, there's two separate things going on here:

(1) What PowerShell version the cmdlets we ship require
(2) What PowerShell version PowerShell we write requires

It's fine for (2) to be as high as we like, really. I think most of the discussion here has been about (1), although it wasn't all clear. I think the answer for (1) is along the lines of "as low as doesn't cause us problems" - although I don't know what that number is.

**Comment by fffej** [comment]
I guess for now "as low as doesn't cause us problems" is the lowest version we can currently ship (just like we do for web browsers).

**Comment by PeterGerrard** [comment]
Sounds like we need two items added:

- Language and tools: Adopt PowerShell 5 when writing internal scripts
- Platforms: Adopt PowerShell 3+ when writing cmdlets for external use

**Comment by ChrisLambrou** [comment]
Might be worth looking at the PFUR data. The session.started event reports the version of PowerShell that our customers actually have available.
