### ISSUE TITLE
[Techniques] Scrum? Kanban?

### ISSUE THREAD

**Issue by ChrisHurley** [red-gate/Tech-Radar#126]
Do we want to be opinionated about how teams plan their work? We use a more Kanban-esque process without explicit sprints, but other teams work differently.

(The answer to this might well be no, but it feels like it's an important part of Techniques)

**Comment by ChrisHurley** [comment]
That's what I was leaning towards, putting both on Adopt - but would be interested if there were any other opinions.

**Comment by sandrastaples** [comment]
The Dev leads have an outstanding action to look at what we want to put on the radar around agile "stuff" and there's a meeting with Jeff planned. I guess the ultimate question is what level would be useful without it being too constraining or confusing? Is it really useful to have loads of different options in adopt, it won't necessarily help you choose which one to apply.

**Comment by nyctef** [comment]
Personally what I'd find useful (or at least really interesting) is a discussion of scrum/kanban/etc and why you might pick one or the other for a particular team, or why you might switch a team from one to the other and what effects you'd expect that to have. That kind of thing might be more suited to some blog posts than the tech radar, though

**Comment by sandrastaples** [comment]
The Dev Leads think we ought to have:

- Scrum in Adopt - many teams use sprints, planning sessions and some even have reviews
- Kanban in Explore - there are no teams currently fully implementing Kanban but some are experimenting woth some aspects of it

**Comment by fffej** [comment]
Do you want to create a PR for this @sandrastaples ?

**Comment by sandrastaples** [comment]
#149  raised.
