### ISSUE TITLE
[Technique] XP

### ISSUE THREAD

**Issue by dnlegge** [red-gate/Tech-Radar#137]
Adopt XP - E[X]treme [P]rogramming

We use Pairing and even some TDD, but there's other elements too

**Comment by fffej** [comment]
I think this one is a bit broad. We adopt some of the practices, but by no means all (never seen anyone do a CRC card session) nor are we disciplined about writing an acceptance test.

I'm going to close this and suggest we break out any practices that we do into "Adopt" and anything we'd like to have a crack at into "Explore".
