### ISSUE TITLE
[Tool] Adopt Impact Mapping

### ISSUE THREAD

**Issue by dnlegge** [red-gate/Tech-Radar#139]
Add Impact Mapping to Adopt

Tie actions to actors and Strategic Goals

Ally Parker ran a Open Space session on this

Oracle Team-to-be

**Comment by ChrisHurley** [comment]
I think we'd have to have it in Explore if a team are going to give it a try.

**Comment by dnlegge** [comment]
Ok

**Comment by garethbragg** [comment]
@dnlegge Are you happy to create a PR to add this?
