### ISSUE TITLE
Build infrastructure

### ISSUE THREAD

**Issue by garethbragg** [red-gate/Tech-Radar#14]
AFAIK, the vast majority of products now use `RedGate.Build`, rather than the old build magic.

How much of this is worth capturing on the tech radar?

My gut says:

* Adopt: RedGate.Build
* Retire: build magic

Worthwhile? Is build magic already dead and I'm living in the past? Is there some other option?

**Comment by MichelleTaylorRG** [comment]
Build magic is almost dead - we're about to start pulling it out of DLM Dashboard, I think that might be the final thing that's left in it.

**Comment by MichelleTaylorRG** [comment]
What is a thing still is what release scripts you use - do you roll your own or are you on the standard release scripts?

**Comment by fffej** [comment]
If it's not dead already then I'd agree with @garethbragg and say let's shove "build magic" in retire and celebrate when we destroy it.

**Comment by garethbragg** [comment]
So it sounds like:

Adopt: Standardised build scripts
Endure: Custom build scripts
Retire: Build magic

(Based on our current definition of _Endure_: "This is no longer how we do things. It is OK for this to be used in Product Development, but don't add more of it and **migrate off it wherever possible**".)

Is there a more concise/meaningful form of "Standardised build scripts"? `RedGate.Build`, perhaps?
