### ISSUE TITLE
Web API vs. ASP.NET Core

### ISSUE THREAD

**Issue by fffej** [red-gate/Tech-Radar#144]
## What change would you like to make to the tech radar?

Based on #107 ASP.NET Core should be in Adopt and Web API should be in retire (albeit a slow burn).

## Why do you believe this is valuable to Redgate?

Web API is going to get less maintenance in the future, ASP.NET Core is where active development is going to happen.

## Where should this be on the tech radar?

Adopt:
* ASP.NET Core

Retire:
* Web API

**Comment by musmuris** [comment]
👍 from me.  We've started looking at what it would take to move COREDev stuff to this a bit.  No plans to start for real yet, but tinkering.

**Comment by fffej** [comment]
Fancy getting the first PR in from CORE Dev @musmuris ? Don't think there's going to be any dissent on this and we're eventually going to have to do it regardless (https://github.com/aspnet/Announcements/issues/324). LTS support ends 2021.

**Comment by ChrisHurley** [comment]
@fffej I think the announcement is saying that the new version of ASP.NET Core will only run on .NET Core, rather than .NET Framework, rather than saying anything about WebApi specifically? But ASP.NET Core on .NET Core is obviously the direction that Microsoft are moving in, yep.

**Comment by fffej** [comment]
I've created a PR for this, but I'd definitely appreciate another pair of eyes since I'm very confused by the naming of projects around ASP.NET!

**Comment by ChrisHurley** [comment]
I merged it before noticing the wording should probably be tweaked, oops... sorry, I should revisit that.
