### ISSUE TITLE
[Tools] edge.js

### ISSUE THREAD

**Issue by nyctef** [red-gate/Tech-Radar#155]
[edge.js](https://github.com/tjanczuk/edge) is a library which allows .NET code to be run from node and vice-versa. It marshals object references and method calls across the .NET/node boundary.

In Figleaf we're currently exploring using edge.js to marshal API requests from our frontend (written in electron/typescript/react) to our backend (written in C#).

This seems to work pretty well, although we have some concerns about edge.js not being "production-ready"  and a bit magic, so we've taken steps to abstract away our use of edge.js. In the frontend we've created a typescript interface for backend API calls which abstracts edge.js away, and in the backend we've tried to write all of the edge entrypoints as "controller" classes, analogous to web MVC controllers from a web framework. This should mean that we can switch technologies without too much pain.

In the future we might replace edge.js with an actual REST API, or with a vscode-style language server thing.

There's a bit more detail in the original decision here: https://github.com/red-gate/data-masking/blob/master/DecisionLog/2017-10-23%20For%20now%20we'll%20use%20edge.js%20to%20communicate%20between%20the%20UI%20and%20a%20C%23%20backend.md

**Comment by fffej** [comment]
Sounds like this should be added to Explore? Unless the team feel like they want an excuse to Retire it?

I agree with the "bit magic" comments, especially when you see comments from Scott Hanselman like this 😄 

> Ah, whatever problem you have. If you have this problem, this solves it.

**Comment by nyctef** [comment]
> Sounds like this should be added to Explore? Unless the team feel like they want an excuse to Retire it?

Yep, sounds about right 👍

Oh, should add a couple of gotchas we've learned about so far:
- When you pass an object from .NET to node, what you get is something that looks like a normal JS object but which actually proxies every property access back to the original C# object. This can cause a huge performance problem if you access a lot of properties in a big array of results (which we were doing in some cases) due to the constant back-and-forth between node and .NET.
- There's a bunch of stuff you can do which Just Works in edge but potentially locks you out of any other tech (eg calling methods on returned objects or throwing exceptions across the boundary). You'll potentially want to avoid these if you're thinking of replacing edge with another technology later.

The solution we found to both of these problems was to explicitly return API results/errors from .NET as JSON strings, and then deserialize those strings into pure JS objects on the node side.

**Comment by cjheppell** [comment]
Looks like I'm a little late to the party, but we actually decided to remove `Edge.js` from our projects. More information as to why is available in the Pull Request detailing the removal: https://github.com/red-gate/foundry-labs/pull/749

That change was then superseded by [this one](https://github.com/red-gate/foundry-labs/pull/761), for the reasons detailed in that PR.
