### ISSUE TITLE
Check for Updates / Autoupdate

### ISSUE THREAD

**Issue by MichelleTaylorRG** [red-gate/Tech-Radar#18]
Where should our 'standard' CfU implementation be on here? Should it be out in Endure and we should be looking into autoupdate - in which case, what are our promising autoupdate options?

**Comment by nyctef** [comment]
Clone has been doing some promising things with autoupdate in the Redgate Client which we should try and devote some more dev effort to - was going to try and pull it into Figleaf but realised we need cfu channels to be supported, so need to do some more work first.

**Comment by garethbragg** [comment]
It feels odd to not have an _Adopt_ answer to this question, but I actually think that's a fair reflection of where we are.

Is there anything else being explored, beyond the (definitely interesting) SQL Clone instance? Electron app autoupdating, maybe?

**Comment by nyctef** [comment]
IIRC foundry use the autoupdate built into `electron-builder`: https://www.electron.build/auto-update. We considered it for Figleaf as well, but assumed we'd be required to build a redgate installer at some point (to integrate with release/licensing/bundling/etc) so skipped straight to that as part of our walking skeleton. The `electron-builder` implementation is extremely slick, though.

**Comment by adrianbanks** [comment]
We need to consider how this works for server tools. Hearing from DBAs on research calls I doubt many of them would want SQL Monitor to auto-update itself. They would however possibly want an easier way to upgrade it.

**Comment by garethbragg** [comment]
@adrianbanks I definitely agree any changes would need serious thought. Just trying to understand (and document) our current state for now, so that thought can be done in a more structured way.

**Comment by mark-raymond** [comment]
@adrianbanks What we've got so far in SQL Clone is when there's an update available, you can just click "Update" in the UI, and it will update in the background. So it's much easier to update. Only those in the Admin role are allowed to initiate the update through the UI.
