### ISSUE TITLE
[Technique] Adopt: Adherence to SOLID

### ISSUE THREAD

**Issue by dnlegge** [red-gate/Tech-Radar#183]
## What change would you like to make to the tech radar?
Formally adopt the components of SOLID

## Why do you believe this is valuable to Redgate?
Good engineering practice

## Where should this be on the tech radar?
Adopt - established, stated elsewhere, but not on this (yet)

### If this should be in the _Explore_ ring, who is committed to exploring it?

**Comment by fffej** [comment]
I'm going to close this out as I believe this is already well-covered by our [CSharpGuidelines](https://github.com/red-gate/CSharpGuidelines)
