### ISSUE TITLE
[Tool] Explore: Chocolatey Windows Package Manager

### ISSUE THREAD

**Issue by dnlegge** [red-gate/Tech-Radar#184]
## What change would you like to make to the tech radar?
Explore the use of chocolatey windows package manager
https://chocolatey.org/

## Why do you believe this is valuable to Redgate?
Standardise package management and deployment and provisioning

## Where should this be on the tech radar?
Explore, 

### If this should be in the _Explore_ ring, who is committed to exploring it?
happy to take this on in the Oracle team-to-be, would encourage others

**Comment by PeterGerrard** [comment]
We already use this in our test infrastructure, could well be adopt

**Comment by nyctef** [comment]
Definitely good to use internally - eg we recommend [using chocolately to get vagrant and virtualbox](https://info.red-gate.com/eng/development-guides/build-release/using-vagrant) when setting up a build environment.

Is this something we should explore for external use as well? (ie wrapping our installers in chocolately packages / distributing our tools some other way?)

**Comment by onatm** [comment]
I use [scoop](https://github.com/lukesampson/scoop) on my workstation as a package manager. Pretty good for _portable_ apps. If you are not planning to use `chocolatey` to deploy `nupkg` artifacts then I strongly recommend you to try `scoop`.

**Comment by fffej** [comment]
I created a PR for this.

I think scoop looks interesting, but it seems to be something any developer could choose to have on their machine for installing apps locally rather than something we'd need to agree on. From my understanding chocolately has the automation side (e.g. on the test infrastructure) sewn up and I'm not sure scoop would give us anything on top of it?

I added @onatm as reviewer, if you disagree please let me know!

**Comment by onatm** [comment]
`scoop` is just a subset of `chocolatey`. The initial suggestion made me think that we only need package management program such as `apt`, `homebrew`, etc. It seems like we want to use something like we want something which can also handle deployment scenarios as well so, `chocolatey` would be the right option for us
