### ISSUE TITLE
[Explore] RESTful APIs

### ISSUE THREAD

**Issue by dnlegge** [red-gate/Tech-Radar#185]
## What change would you like to make to the tech radar?
Use of RESTful APIs as a way to decouple UI and backend

## Why do you believe this is valuable to Redgate?
Good practice, decoupling, powerful technique, cross-platform

## Where should this be on the tech radar?
Whilst established practice in industry, probably explore in red-gate
Don't know which quadrant this belongs in.

### If this should be in the _Explore_ ring, who is committed to exploring it?
Quite possibly in the Oracle team-to-be, but depends on what we work on

**Comment by onatm** [comment]
I think this should be in Adopt. SQL Clone has a RESTful API for a quite some time. Also, @red-gate/spiders built their RESTful API as well.

**Comment by garethbragg** [comment]
Sounds ready for _Adopt_, which is nice!

Anyone keen to open a PR?
