### ISSUE TITLE
[Techniques] Continuous Delivery

### ISSUE THREAD

**Issue by raganmcgill** [red-gate/Tech-Radar#186]
## What change would you like to make to the tech radar?
Add it to the radar

## Why do you believe this is valuable to Redgate?
Continuous Delivery aims to automate all the repetitive, error-prone activities that humans do that can lead to inconsistent, unreliable, or unrepeatable processes.  Our test suites needs to cover enough of the codebase; acting as an enabler for automated deployments. The trigger is still manual but once a deployment is started there shouldn't be a need for human intervention.  

Value presents itself as the complexity of deploying software has been taken away.  Time investments in releases become cheap and teams can release more often, thus accelerating the feedback loop.  There is much less pressure on decisions for small changes, hence encouraging iterating faster.

## Where should this be on the tech radar?
Adopt

**Comment by nyctef** [comment]
👍 Definitely a good idea, but this sounds like it's mostly a combination of #117 ("master is always releasable") and #38 ("one-step release scripts") - not sure if there's something new to add to the radar here?
