### ISSUE TITLE
[Techniques] Visual Controls; Team Dashboards and Information Radiators

### ISSUE THREAD

**Issue by raganmcgill** [red-gate/Tech-Radar#188]
## What change would you like to make to the tech radar?
Add it to the radar

## Why do you believe this is valuable to Redgate?
Intensive use of information radiators convey two messages in addition to the information itself:

Our teams have nothing to hide from their visitors (stakeholders, other teams, etc...)
Our teams have nothing to hide from themselves; they acknowledges and confronts problems

The intent is to clearly and succinctly disclose relevant information about current state, progress and what the horizon is looking like.  Benefits of this include promotion of ownership among the team members as well as the encouragement of conversations, yielding useful ideas.

Team Dashboards and Information Radiators are a great space for the Porpoise, Meerkat and Jellyfish to roam :) 

## Where should this be on the tech radar?
Adopt

**Comment by garethbragg** [comment]
@raganmcgill sounds good to me - happy to create a PR?

**Comment by ChrisHurley** [comment]
(It would be awesome if we could standardise on a platform for displaying dashboard metrics which had all the usual data sources ready to go, too)

**Comment by raganmcgill** [comment]
> @raganmcgill sounds good to me - happy to create a PR?

sure am
