### ISSUE TITLE
[Techniques] Story Points

### ISSUE THREAD

**Issue by cj-smithy** [red-gate/Tech-Radar#193]
## What change would you like to make to the tech radar?
Story Points (especially as an effort estimation technique) should be added to Endure.
## Why do you believe this is valuable to Redgate?
[Story Points](https://www.mountaingoatsoftware.com/blog/what-are-story-points) are cool in some environments. but I'd argue not ours! There's lot of reasons why the Dev Leads and I think that (here are a [few](https://medium.com/@mdalmijn/12-common-mistakes-made-when-using-story-points-f0bb9212d2f7)) but the headlines are - they get conflated to mean stuff they don't mean, they don't really help estimation when we focus on outcomes/agility and it's better (in all kinds of reasons) to just focus on making pieces of work/value really small.

Story Points should be in Endure, for me. So, if teams are making use of them and they are peppered all over their backlog, then that's fine. But I would not recommend a new team to use them - instead, focus on splitting stories/work down as small as you can. Then count the number for stories & measure cycle time to do estimation and measure performance of the system,

## Where should this be on the tech radar?
In endure. 
### If this should be in the _Explore_ ring, who is committed to exploring it?

**Comment by garethbragg** [comment]
Does anyone actually use story points anymore?

**Comment by cj-smithy** [comment]
I've heard a couple of teams talk about "estimation and Fibonacci numbers" in the same breath... but I cannot remember which team that was. More than happy for this to be in "Retire/Avoid", as its a bit of the scrum framework (add ons?) that I don't think suits where we are now.
"Yes" to adding "splitting stories/work down as small as you can", etc! I did think one of the other Dev Leads had taken that as an action (but then it might also have been my job).

**Comment by sandrastaples** [comment]
Vertical slicing is #177
