### ISSUE TITLE
Assertion library for unit testing in C# (Shouldly / FluentAssertions)

### ISSUE THREAD

**Issue by Greg-Smulko** [red-gate/Tech-Radar#198]
## What change would you like to make to the tech radar?
Adopt [Shouldly ](https://shouldly.readthedocs.io/en/latest/) or [FluentAssertions](https://fluentassertions.com/).

## Why do you believe this is valuable to Redgate?
As described by @nyctef [here](https://github.com/red-gate/Tech-Radar/issues/27#issuecomment-435830651).

The readability of tests is much better with these libraries.
Instead of: 
```
Assert.That(contestant.Points, Is.EqualTo(1337));
// Expected 1337 but was 0
```
there is:
```
contestant.Points.ShouldBe(1337);
// contestant.Points should be 1337 but was 0
```

Also compare:
```
Assert.That(map.IndexOfValue("boo"), Is.EqualTo(2));    // -> Expected 2 but was 1
map.IndexOfValue("boo").ShouldBe(2);                    // -> map.IndexOfValue("boo") should be 2 but was 1
```

Shouldly is [used by Versioning and Foundry](https://codesearch.red-gate.com/?q=Shouldly&i=nope&files=&repos=).
FluentAssertions are [used in the CompareEngine, FigLeaf, Sql Dashboard and a bit in Monitor](https://codesearch.red-gate.com/?q=FluentAssertions&i=nope&files=&repos=)

[Comparison of Shouldly and FluentAssertions](https://dotnet.libhunt.com/compare-shouldly-vs-fluentassertions) - FluentAssertions seem to be more popular and a bit more active.

## Where should this be on the tech radar?
Tools - Adopt

### If this should be in the _Explore_ ring, who is committed to exploring it?
n/a

**Comment by Greg-Smulko** [comment]
@alextercete, you had strong opinions in favour of Shouldly, AFAIR. 
My personal preference was FluentAssertions at that point, but I don't really mind neither, as long as `Assert.That` is no longer recommended. :)

**Comment by garethbragg** [comment]
How can we decide which of these we should adopt?

What happens to the one we don't put in adopt? Endure, I guess?

Is it suitable to adopt two tools for the same thing?

**Comment by fffej** [comment]
Likewise I don't mind - I'd prefer to put one in Endure and one in Adopt simply because it seems daft to diverge on this.

I'd vote for Shoudly because I prefer the way the assertions read.

**Comment by nyctef** [comment]
It looks like FluentAssertions [has pinched Shouldly's killer feature in v5](https://www.continuousimprover.com/2018/02/fluent-assertions-50-best-unit-test.html#subject-identification) so I'm not currently aware of a reason to prefer Shouldly - FluentAssertions has a wider variety of assertions and it doesn't look like Shouldly has anything like [`foo.Should().BeEquivalentTo(bar)`](https://fluentassertions.com/documentation/#object-graph-comparison) which we've found to be very useful (although this [might be coming soon](https://github.com/shouldly/shouldly/pull/411)).

**Comment by alextercete** [comment]
> @alextercete, you had strong opinions in favour of Shouldly, AFAIR.
> My personal preference was FluentAssertions at that point, but I don't really mind neither, as long as `Assert.That` is no longer recommended. :)

@Greg-Smulko Like @fffej, I prefer the way the assertions read in Shouldly. Also, the error messages were more descriptive (although FluentAssertions might have caught up since I last saw it).

**Comment by fffej** [comment]
I simply like the example of `contestant.Points.ShouldBe(1337)` vs. `contents.Points.Should().Be(1337)`

**Comment by acoop133** [comment]
It doesnt seem like `Shouldly` has the ability to equality check class fields like `FluentAssertions` `Should().BeEquivalentTo()`
Which is something that i found to be really useful for checking equality between classes of a different instance without having to write an overide or a manualy check each field.

example https://medium.com/@pjbgf/asserting-equality-in-your-c-unit-tests-837b423024bf

**Comment by Greg-Smulko** [comment]
@acoop133, as @nyctef commented above, the `BeEquivalentTo()` feature seems to be available now (or at least merged to master, if not released yet): https://github.com/shouldly/shouldly/pull/411

**Comment by nyctef** [comment]
> @acoop133, as @nyctef commented above, the `BeEquivalentTo()` feature seems to be available now (or at least merged to master, if not released yet): [shouldly/shouldly#411](https://github.com/shouldly/shouldly/pull/411)

Nice - judging by [the v3 release history](https://www.nuget.org/packages/Shouldly/) it might be half a year before it actually makes it into a stable version, though

I think FluentAssertions still has a wider range of assertions available, which is nice, but that was the one thing that would block us from using Shouldly. It looks like the Shouldly implementation is still pretty basic compared to the FluentAssertions one, though, so it would be worth double-checking that it can actually replace what we're doing at the moment if we wanted to migrate.

**Comment by Greg-Smulko** [comment]
OK, let's try to summarize it a bit:

**FluentAssertions**
Pros:
- supports `ShouldBeEquivalentTo()`, and in general wider range of assertions available
- seems to be more popular and a bit more active

**Shouldly**
Pros:
- reads a bit nicer: `id.ShouldBe(1);` compared to `id.Should().Be(1);`
- arguably better string assertions (see screenshot below) - however from my experience it's not so useful for long strings anyway as it may seem

![image](https://user-images.githubusercontent.com/26791344/51315160-6b800e80-1a49-11e9-8260-90bd4ed479ac.png)

Based on the above, I'd propose to put `FluentAssertions` to the Adopt category and `Shouldly` to the Endure one, with the main reason being `ShouldBeEquivalentTo()`.

If nobody strongly objects, I'll open a PR for it early next week.

**Comment by fffej** [comment]
Sounds like a good summary @Greg-Smulko and gets my 👍

**Comment by twalsh92** [comment]
Currently in SQL Prompt, we just use standard NUnit assertions in all our tests. I'm currently trying out FluentAssertions in one of our test classes. I'm happy to report back how that goes.
