### ISSUE TITLE
Licensing models

### ISSUE THREAD

**Issue by MichelleTaylorRG** [red-gate/Tech-Radar#21]
We're enduring serial key based licensing and adopting login licensing, I think? Should we put other licensing considerations (user vs per-server vs other size-calculation models, perpetual and S&U vs subscription) on here, or is that too distant from tech / decisions teams can make themselves?

**Comment by StephanieHerr** [comment]
Ben Rees and the P&P committee have done some work on this - https://info.red-gate.com/rg/blog/2018/08/updated-pricing-strategy-for-redgate

**Comment by fffej** [comment]
I'm going to close this as off-topic (mostly for the reasons that @MichelleTaylorRG mentioned). Let's leave this to the Pricing and Packaging committee and restrict the radar to the technical decisions that teams can take.
