### ISSUE TITLE
[Technologies] Move edge.js to Retire

### ISSUE THREAD

**Issue by ChrisHurley** [red-gate/Tech-Radar#210]
## What change would you like to make to the tech radar?
edge.js should be moved from Explore to Retire (or removed).

## Why do you believe this is *not* valuable to Redgate?
* Foundry have [removed edge.js](https://github.com/red-gate/foundry-labs/pull/749)
* Figleaf are [removing edge.js](https://github.com/red-gate/ArchitectureDecisions/blob/f9b55bd/text/000003%20-%20Figleaf%20replace%20edgejs%20with%20webserver.md)

The teams who were exploring it have encountered some drawbacks (most notably that it isn't actively updated) and decided not to use it, therefore it should be moved to Retire (or removed from the radar if it's already been retired completely).

**Comment by fffej** [comment]
Retirement celebrations 😄 

@ChrisHurley Would you be able to create a PR for this?

**Comment by ChrisHurley** [comment]
Ok! The only question I had was whether we actually have any more `edge.js` or if it's already retired - sounds like it might already be gone?

**Comment by fffej** [comment]
I think it's proper dead 😄 Last time I checked on codesearch.red-gate.com it was only in the Foundry/Figleaf repositories.

**Comment by ChrisHurley** [comment]
#215 created!

**Comment by ChrisHurley** [comment]
Closed via #215
