### ISSUE TITLE
[Techniques] Pull Request Templates

### ISSUE THREAD

**Issue by twalsh92** [red-gate/Tech-Radar#213]
## What change would you like to make to the tech radar?
Add "Pull Request Templates".

## Why do you believe this is valuable to Redgate?
Using templates in pull requests makes sure every PR that gets created goes through the same process. This can help mitigate the risks of release notes not being added, documentation being missed and testing not described. It also makes it much easier to understand past changes to the codebase.

## Where should this be on the tech radar?
_Adopt_.

### If this should be in the _Explore_ ring, who is committed to exploring it?

**Comment by nyctef** [comment]
I think this was just added by #209 :)

**Comment by fffej** [comment]
Yup, @samblackburn beat you to it 😄
