### ISSUE TITLE
[Languages and frameworks] Add Semantic UI to Explore

### ISSUE THREAD

**Issue by joselima** [red-gate/Tech-Radar#214]
## What change would you like to make to the tech radar?
Add Semantic UI

## Why do you believe this is valuable to Redgate?
The work done by Andrew/Ian to evaluate Semantic UI React and Bootstrap React concluded that Semantic UI React was the best choice at this point in time. Read more about the project [here ](https://docs.google.com/document/d/1yu9yG0HKxRfPi9c8bWUw9VN82MFQysVXqv5A08LnnzY/edit#heading=h.pgjipvm3pklo) and their conclusions [here](https://github.com/red-gate/honeycomb-react/blob/timebox-spike/timebox/conclusions.md).

## Where should this be on the tech radar?
Explore

### If this should be in the _Explore_ ring, who is committed to exploring it?
Discussion below

**Comment by joselima** [comment]
@ChrisHurley would this be something Clone could commit to once the work is complete? The obvious candidate would've been Figleaf but not anymore. @MattGodfrey may also have some thoughts?

**Comment by ChrisHurley** [comment]
We unfortunately missed the boat a bit with our dashboard rewrite last year, which is when we hoped to use Honeycomb React. I'm sure we can try it the next time we have UI work to do once it's Honeycombed, but that will probably be Q2 or later?

**Comment by ChrisHurley** [comment]
(We are doing some UI work in Q1, FWIW, but I suspect that may be too soon - but if it's done in time we can take a look!)

**Comment by joselima** [comment]
@andrew-farries could Data Catalog be a candidate for this now we have an initial set of components? And if so, could they commit to exploring this?

**Comment by allymparker** [comment]
Can we merge this?

**Comment by fffej** [comment]
Resolved by #251
