### ISSUE TITLE
IE10 to Endure

### ISSUE THREAD

**Issue by fffej** [red-gate/Tech-Radar#216]
## What change would you like to make to the tech radar?

Move IE10 to endure

## Why do you believe this is valuable to Redgate?

It's tidying up the sentiment. Currently IE10 is in retire which means we should go around and remove the IE10 specific code paths from our applications. This isn't actively doing harm at the moment so moving it to Endure reflects this. 

### If this should be in the _Explore_ ring, who is committed to exploring it?

N/A

**Comment by garethbragg** [comment]
Resolved by #223
