### ISSUE TITLE
Move Pre ES6 to Endure

### ISSUE THREAD

**Issue by fffej** [red-gate/Tech-Radar#217]
## What change would you like to make to the tech radar?

Move JavaScript Pre ES6 to Endure

## Why do you believe this is valuable to Redgate?

We shouldn't be rewriting all the JavaScript to ES6 style so moving it to Endure better reflects the sentiment.

## Where should this be on the tech radar?

Endure

**Comment by garethbragg** [comment]
Resolved by #223
