### ISSUE TITLE
Supported SQL Server and SSMS versions - and other platform support issues

### ISSUE THREAD

**Issue by MichelleTaylorRG** [red-gate/Tech-Radar#22]
https://info.red-gate.com/eng/development-policies/platforms-and-supported-versions looks like some of its contents may now belong here?

**Comment by fffej** [comment]
Perfect - that looks like an easy PR for someone if they want to make it?

**Comment by nyctef** [comment]
Possible addition: Explore net471 ([since it supports .NET Standard 2.0 much better than net461 does](https://info.red-gate.com/eng/development-guides/net-standard))

Currently being used by Figleaf (and possibly other products as well)
