### ISSUE TITLE
[Library] Retire TaskParallelLibrary

### ISSUE THREAD

**Issue by fffej** [red-gate/Tech-Radar#227]
## What change would you like to make to the tech radar?

Retire `TaskParallelLibrary`

## Why do you believe this is valuable to Redgate?

We shouldn't include references to libraries we don't need and since we're all up to date > .NET Framework 3.5 we don't need this.

## Where should this be on the tech radar?

Retire.

### If this should be in the _Explore_ ring, who is committed to exploring it?

**Comment by garethbragg** [comment]
How widely used is `TaskParallelLibrary`?
How easy is it to remove?
How much effort will it be to retire it?
How/when do we expect this work to get done?

(Totally supportive, but I don't want to open a "Pull `TaskParallelLibrary` back to _Endure_" PR in a few weeks 😄 )

**Comment by fffej** [comment]
https://codesearch.red-gate.com/?q=TaskParallelLibrary&i=nope&files=&repos= shows it's used in migration blocks, simple auto updater, compare and dependency tracker, monitor tests, soc  and a fair few more.

Removing it should be trivial - if the library is targeting >3.5 then it's just delete the dependency.

Ideally let's get this done by the next iteration of the tech radar (dependent on all the other things!).

**Comment by fffej** [comment]
I've got a feeling that @juliahayward might have already nuked this from all those repos?

**Comment by juliahayward** [comment]
Nuking, but not there yet

**Comment by juliahayward** [comment]
In fact this is also tied up with our chain of dependencies using System.Threading 1.0.2586 from the TPL backport - I suspect these also need to be removed. SDT is building but with warnings about making an arbitrary choice of how to resolve System.Threading (fortunately it's defaulting to the 4.0 builtin)

**Comment by juliahayward** [comment]
Any products that get it transitively from HoneyComb-Winforms will need to bump to 1.1.469 or greater

**Comment by fffej** [comment]
Resolved by #254
