### ISSUE TITLE
[Tools] Postman

### ISSUE THREAD

**Issue by MikielAgutu** [red-gate/Tech-Radar#228]
## What change would you like to make to the tech radar?

Introduce Postman https://www.getpostman.com/

## Why do you believe this is valuable to Redgate?

It's a tool for manual and automated testing of APIs. As we strive to be API first, having a go-to tool for this sort of thing makes sense.

## Where should this be on the tech radar?
Explore

### If this should be in the _Explore_ ring, who is committed to exploring it?

The Versioning Teams (Team U.P., Orca, and Autobots) are currently exploring Postman.

**Comment by adrianbanks** [comment]
As an alternative to this if using Rider, it has a built in [HTTP client](https://www.jetbrains.com/help/rider/Http_client_in__product__code_editor.html). An added benefit is that the requests are just `.http` files that can be added to a repository to be shared.

**Comment by fffej** [comment]
Excellent - @MikielAgutu do you want to create a PR and I'll merge it?

**Comment by Greg-Smulko** [comment]
Closed by #248.
