### ISSUE TITLE
Non-web UI

### ISSUE THREAD

**Issue by MichelleTaylorRG** [red-gate/Tech-Radar#23]
Is this something that is in Endure in general, both WPF and Winforms? 

What about for SSMS / VS plugins - is WPF still an Adopt approach in that specific case? 

What's our position on various ways of making web UIs in standalone tools (e.g. Electron, whatever it is that ANTS and Monitor uses)? 

Can we all agree that CEF belongs in Retire?

**Comment by fffej** [comment]
👍  for CEF in Retire.

Electron is probably in Explore (we've only got one app using it and haven't shipped a lot yet?). Would you agree @smobs?

For plugins I agree with @MichelleTaylorRG - it's probably the UI framework of the host thing we're plugging into, and I think that's WPF in all cases).

**Comment by nyctef** [comment]
> it's probably the UI framework of the host thing we're plugging into, and I think that's WPF in all cases).

~~SQL Ops Studio~~ Azure Data Studio [might the exception here](https://medium.com/ingeniouslysimple/how-we-built-an-extension-for-sql-operations-studio-f93532ce4456), but yeah generally WPF (without any attempts at cross-process UI remoting or other shenanigans) seems to be the right answer there.

**Comment by garethbragg** [comment]
How about:

Retire: CEF
Retire: Winforms
Adopt: WPF
Adopt: Electron

Probably with a mention in the WPF/Electron descriptions about when/where they are the preferred option?

**Comment by MichelleTaylorRG** [comment]
I guess the other question is 'are these frameworks or tools?' - I'm not 100% sure what quadrant they belong in

**Comment by fffej** [comment]
On the subject of which quadrant, let's say frameworks (because it's a bit arbitrary anyway!).

@MichelleTaylorRG If WinForms is in retire, does Toolbelt have any products in that area? The implication is that we would seek to get that technology out of the business asap.

**Comment by allymparker** [comment]
> Adopt: Electron
As much as I prefer web UI dev over WPF/winforms, I'm not sure how strongly "proven" this is as a choice yet?  ThoughtWorks had it in Assess, but have [archived it from their tech radar](https://www.thoughtworks.com/radar/platforms/electron) (although I'm not 100% on the significance of this)

Just to make things a bit more complicated, at what point does a "tool" move from being a desktop app installed as an executable on a users machine, to being deployed to a central server and being delivered via a web browser?  

I suppose SQM/Clone/etc could have delivered it's UI via Electron, and (maybe?) FigLeaf could have been delivered as a self or IIS hosted web app...

**Comment by ChrisHurley** [comment]
(Slack, Discord etc. are interesting examples there - although it's a web app, and the majority of the functionality is available without installing anything, there's value in having a local Electron version too to integrate better with the OS)

**Comment by MichelleTaylorRG** [comment]
We have a _lot_ of WinForms stuff and have no interest in messing around with it. We're much keener to properly retire CEF (and salt the earth behind it), but even that is pretty low down the priority chart - essentially we're not very interested in anything that means we have to rewrite the UI of a minnow from scratch because most minnows don't see much work done on them and so we won't see much benefit from doing so.
