### ISSUE TITLE
[Library] Definitely retire Rhino Mocks

### ISSUE THREAD

**Issue by fffej** [red-gate/Tech-Radar#233]
## What change would you like to make to the tech radar?

I'd like to move `Rhino.Mocks` back to Retire but with better documentation on why 😄 

We should retire `Rhino.Mocks` when we're trying to move corresponding libraries over to .NET Core. The reason is that `Rhino.Mocks` does [not support .NET Core](https://stackoverflow.com/questions/52159272/rhino-mock-compatibility-with-netcore).

## Why do you believe this is valuable to Redgate?

As part of our .NET Core work.

## Where should this be on the tech radar?

Retire. With caveats.

### If this should be in the _Explore_ ring, who is committed to exploring it?

N/A

**Comment by garethbragg** [comment]
Standard caveat: I'm _super onboard_ with retiring stuff, but trying to be critical.

I think the "caveats" you mention actually mean this is best left in _Endure_.

> Endure - This is no longer how we do things. It is OK for this to be used in Product Development, but don't add more of it and **migrate off it wherever possible.**
> 
> Retire - Don't use this technology! If you are using it then **you should be spending some time migrating away from this**. [sic]

(emphasis added.)

Moving something to run on .Net Core will mean Rhino Mocks must be removed, enforcing the "migrate of fit wherever possible" part of _Endure_. I think we'd continue to _Endure_ Rhino Mocks anywhere we don't target .Net Core.

If we're not *actively planning to prioritise retiring something*, then I'm not sure it should be in _Retire_.

**Comment by fffej** [comment]
I'm happy with that, let's close this down.
