### ISSUE TITLE
[Library] Remove Fody from the Tech Radar

### ISSUE THREAD

**Issue by fffej** [red-gate/Tech-Radar#234]
## What change would you like to make to the tech radar?

Remove Fody

## Why do you believe this is valuable to Redgate?

Because we've retired it! 🎆 

## Where should this be on the tech radar?

N/A

### If this should be in the _Explore_ ring, who is committed to exploring it?

N/A

**Comment by fffej** [comment]
@juliahayward Could you create a PR? 😄

**Comment by nyctef** [comment]
PR created and merged: https://github.com/red-gate/Tech-Radar/pull/235
