### ISSUE TITLE
[Tool] Docker

### ISSUE THREAD

**Issue by nyctef** [red-gate/Tech-Radar#244]
## What change would you like to make to the tech radar?

Add more detail around Docker on the radar - possibly split it up into different entries for internal/external use:

- Building products around Docker (eg [spawn](https://www.redgatefoundry.com/apps/spawn)) - I think this is what our current entry refers to
- Shipping products inside of Docker containers (a new way of distributing RG commandlines)
- Using Docker internally for build/test (eg Team Orca have started running some linux unit tests inside a docker container as part of the SCA build)

## Why do you believe this is valuable to Redgate?

Adding a bit more clarity + new avenues to explore Docker containers

## Where should this be on the tech radar?

Staying in 'Explore' for now

### If this should be in the _Explore_ ring, who is committed to exploring it?

In addition to the Sharks, Team Orca is now tentatively looking into using docker containers for building/distributing the new SCA for Oracle commandline

**Comment by fffej** [comment]
Completely agree, PR welcome 😄
