### ISSUE TITLE
[Tools] Adopt KeePass

### ISSUE THREAD

**Issue by Greg-Smulko** [red-gate/Tech-Radar#249]
## What change would you like to make to the tech radar?
Add [KeePass](https://keepass.info/) to the Tools section as Adopt.

## Why do you believe this is valuable to Redgate?
A few teams adopted KeePass already (e.g. Versioning, sql monitor, The Spiders, foundry, ...).
This allows to store all passwords in one encrypted file in GitHub, so you need to care about one master password only, rather than multiple passwords to multiple resources.

References:
* https://github.com/red-gate/SqlDataCatalog/pull/1479
* https://github.com/search?q=org%3Ared-gate+keepass&type=Code
* https://github.com/search?q=org%3Ared-gate+kdbx&type=Code

## Where should this be on the tech radar?
Tools-Adopt

### If this should be in the _Explore_ ring, who is committed to exploring it?
n/a

**Comment by fffej** [comment]
PR welcome, don't think there's much to discuss here 😄
