### ISSUE TITLE
[Techniques] Semantic Versioning 2.0.0 (SemVer)

### ISSUE THREAD

**Issue by Greg-Smulko** [red-gate/Tech-Radar#252]
## What change would you like to make to the tech radar?
Add **Semantic Versioning 2.0.0** - at least for the internal tools and libraries.

## Why do you believe this is valuable to Redgate?
[Semantic Versioning](https://semver.org/) is a de-facto industry standard for versioning applications.
AFAIK, we use it for most of our internal libraries anyway.
In terms of products, Semantic Versioning may be in conflict with marketing needs.

## Where should this be on the tech radar?
Techniques/Adopt

### If this should be in the _Explore_ ring, who is committed to exploring it?
n/a

**Comment by nyctef** [comment]
I think this is generally a good idea, with the caveat that semantic versioning .NET assemblies often turns out to be a lot harder than it sounds [[1]](https://info.red-gate.com/eng/development-policies/libraries/versioning-assemblies) [[2]](https://info.red-gate.com/product-division/product-teams/the-toolbelt-team/the-semantic-versioning-predicament)

**Comment by nyctef** [comment]
> In terms of products, Semantic Versioning may be in conflict with marketing needs.

For some of our code, we may need to maintain both a public marketing version and an internal semantic version (eg like VS does: https://en.wikipedia.org/wiki/Microsoft_Visual_Studio#History). I think this is generally fine. For the most part though, products should end up with a marketing version and libraries should get a semantic version.

**Comment by fffej** [comment]
I agree, we should be aspiring to do this as a practice.

As @nyctef says strong-naming means that SemVer doesn't quite give us the benefits it should, but regardless I think it's good practice to think about API versioning and this seems the most sensible way I've seen! PR welcome to close this issue out.
