### ISSUE TITLE
Logging framework (.Net)

### ISSUE THREAD

**Issue by fredjeronimo** [red-gate/Tech-Radar#26]
We have a single one in Prompt:

* [Log4Net](https://logging.apache.org/log4net/) - Adopt

I've used others elsewhere (e.g. [NLog](https://nlog-project.org/)), but currently we have found no need to look into them here.

**Comment by ChrisHurley** [comment]
We also use Serilog in Clone (although we admittedly don't make as much use of its structured logging as we could).

**Comment by nyctef** [comment]
Figleaf currently uses Serilog as well (pretty much just picked at random) - we use the structured logging to occasionally dump out an entire data structure we can't be bothered to serialise properly, but that's about it.

On the other hand, here's our current logging advice from the info site:

> It's important we have common standards for where we log information. It helps support and customers find and diagnose issues. However, we don't believe there is one logging library to rule them all - each team has different circumstances (e.g. web app vs. desktop application vs. server tool).
> - Application should log output into %AppData%\Local\Red Gate\Logs\\\<PRODUCT NAME>
> - Libraries must NOT depend on a specific logging implementation, instead providing a suitable interface for consumers to inject
> - Applications can choose a logging framework to suit their requirements
> - Don't take a read lock (it makes it harder for customers to get logs to us if they're locked)

Not sure if now's the time to standardize on a logging library between products, but I think we should stick with that middle point and not let libraries choose any particular library to support.

**Comment by fffej** [comment]
Log4Net currently isn't .NET Standard 2.0 compatible and hasn't been touched since [July 1 2017](https://github.com/apache/logging-log4net/).

[SeriLog](https://github.com/serilog/serilog) is more active (in terms of commits, stars and forks).

For this reason I'd say:
* SeriLog (Adopt)
* Log4Net (Endure)

I can't see much benefit in retiring and having only a single logging library (though happy to have my mind changed).

As @nyctef mentioned I still believe in our current logging advice of "Libraries must NOT depend on a specific logging implementation".

**Comment by Michael-Upton** [comment]
log4net also forces (?) use of a single static logging root, which causes massive problems in the SSMS plugins (e.g. many of SOCs log outputs end up in SQL Test)

**Comment by fffej** [comment]
@Michael-Upton Would you say that's strong enough to change the status to retire Log4Net?

**Comment by Greg-Smulko** [comment]
@Michael-Upton @fffej , regarding:
> log4net also forces (?) use of a single static logging root, which causes massive problems in the SSMS plugins (e.g. many of SOCs log outputs end up in SQL Test)

While I appreciate that it is a real problem, I don't think that's an issue with log4net, but rather how we use it.
See: https://redgate.slack.com/archives/C83J3KE82/p1539864322000100, basically Logging Repository may be a solution: https://logging.apache.org/log4net/release/manual/repositories.html

**Comment by allymparker** [comment]
FWIW Monitor is using L4N, but I have no strong feelings one way or another!

**Comment by allymparker** [comment]
@fffej Could you elaborate on: 
>Libraries must NOT depend on a specific logging implementation, instead providing a suitable interface for consumers to inject

What's meant by libraries in this case?

**Comment by fffej** [comment]
@allymparker In that case I was thinking NuGet packages (I think it's weird that using a particular package would force my choice of logging framework).
