### ISSUE TITLE
Rename category "Languages and frameworks"

### ISSUE THREAD

**Issue by Greg-Smulko** [red-gate/Tech-Radar#261]
Rename category "Languages and frameworks" to "Languages, frameworks and libraries".

In this category, there is a lot of libraries, but it's confusing whether a library should be in the category "Languages and frameworks" or "Tools". An example here: #259.

**Comment by nyctef** [comment]
So the way I understand it, libraries should only go on the main radar if they're "architecturally significant" (eg switching from JQuery to React is a Big Deal). This is kind of the library/framework distinction (although [everyone has a slightly different idea of the difference](https://stackoverflow.com/questions/148747/what-is-the-difference-between-a-framework-and-a-library)).

If a given "library" isn't a framework, then it can go into `radar_libraries.csv` instead, [or just be ignored from the radar entirely](https://github.com/red-gate/Tech-Radar#frequently-asked-questions). 

Of course, we may decide we want to do something different here. But that's how I think it works at the moment.

**Comment by Greg-Smulko** [comment]
Oh, I wasn't aware of [radar_libraries.csv](https://github.com/red-gate/Tech-Radar/blob/master/radar_libraries.csv)!

So then I propose to do the below instead:
1. clean-up the `radar.csv` file from libraries by moving them to `radar_libraries.csv`.
2. add the info to the PR template that "if you're adding a library that's not architecturally significant, add it to radar_libraries.csv instead".
3. do something more to make radar_libraries more discoverable:
 -  Readme? 
 - http://techradar-libraries.red-gate.com/ ?
 - ... ?

Thoughts?

**Comment by garethbragg** [comment]
I've also updated the PR template to ask about the libraries radar file.
