### ISSUE TITLE
[Techniques] Remove "Scrum"

### ISSUE THREAD

**Issue by garethbragg** [red-gate/Tech-Radar#274]
## What change would you like to make to the tech radar?
_puts on flame-protective clothing_
Should we remove Scrum from the tech radar, and replace it with the actual practices we use.

## Why do you believe this is valuable to Redgate?
I don't believe anyone at Redgate actually uses Scrum.

We intermittently use some of the practices:
* Daily stand ups are globally expected (and already on the tech radar as its own item)
* Sprints/sprint planning, backlogs, reviews, and retrospectives are used optionally as part of a team's process (some of these are also on the radar already)

However, I think saying we "adopt scrum" sets expectations that we do not meet. Specifically:
* Sprints/backlogs management/etc. being a defined part of our processes
* Adoption of scrum roles (clear/explicit scrum masters, product owners)
* Non-core things that are associated with scrum (burndown/ups, velocity tracking, etc.)

## Where should this be on the tech radar?
The relevant bits of Scrum should be in _Adopt_.

### If this should be in the _Explore_ ring, who is committed to exploring it?
N/A.

**Comment by garethbragg** [comment]
(I imagine there's an argument to do this with Kanban as well, but that should be a separate issue IMO.)

**Comment by fffej** [comment]
👍 to this.

**Comment by garethbragg** [comment]
Would be useful to get some Dev Lead input on this.

💁‍♂ ✨ _summons @Michael-Upton_ ✨
