### ISSUE TITLE
[Techniques] "Mobbing"

### ISSUE THREAD

**Issue by twalsh92** [red-gate/Tech-Radar#281]
## What change would you like to make to the tech radar?
Move "Mobbing" to adopt.

## Why do you believe this is valuable to Redgate?
Several teams have done lots of experiments with mobbing and it seems to have worked really well. Following Woody Zuill's workshop most if not all teams are planning to do a lot more of it. Therefore I think it can be moved out of "Explore".

Like any techniques, it shouldn't be applied blanket style, but we've found it works well in the following scenarios:

- You're working in an unknown area of the codebase
- You're trying to onboard a new starter

## Where should this be on the tech radar?
Adopt

### If this should be in the _Explore_ ring, who is committed to exploring it?

**Comment by garethbragg** [comment]
Is there any useful guidance you could give on when mobbing is/isn't a good thing to do?

**Comment by nyctef** [comment]
We wrote a blog post on mobbing in the Orca team a while back, which has some advice: https://medium.com/ingeniouslysimple/a-mob-of-orcas-fdfe0bbdc599

I've got some further thoughts since then which I'll try to collect and write here

**Comment by nyctef** [comment]
To add to the above:
One big thing I picked up from Woody Zuill's workshop today is that mob programming requires really good team communication.
Woody suggested that teams actually start off practicing a strict [Randori Kata](http://codingdojo.org/RandoriKata/) where the team cycles through driver, navigator and observer roles every few minutes. The catch is that (at least to begin with) only the navigator can speak - the hard part is practising patience when you have a really good idea but possibly need to wait twenty minutes to suggest it! However this kind of discipline is vital if you want to have properly productive discussions in discussions in freeform mob programming.

**Comment by Dave-Rook** [comment]
Is part of the problem here "adopt" @nyctef ? Please see https://github.com/red-gate/Tech-Radar/issues/283

**Comment by nyctef** [comment]
After some in-person discussion I should clarify I still think we should adopt mob programming - these are just concerns about how it can go wrong. I think working through and addressing these concerns is a part of a team getting good at mobbing.

**Comment by smobs** [comment]
> One big thing I picked up from Woody Zuill's workshop today is that mob programming requires really good team communication.

We could turn this on its head: Teams should be striving for good communication, and mob programming is one way to expose problems.

**Comment by Dave-Rook** [comment]
I understand there are some problems - and I totally agree with everything said. I'm not sure if mobbing will be done solely by any team, but it does seem that we have explored and it should now be adopted as an extra tool for the toolbox

**Comment by garethbragg** [comment]
This has been updated on the tech radar, so let's close this issue.
