### ISSUE TITLE
Rename "Adopt" to "Available"

### ISSUE THREAD

**Issue by fffej** [red-gate/Tech-Radar#283]
@Dave-Rook highlighted to me that `Adopt` might be the wrong term. `Adopt` implies that we should use a particular technique regardless. 

For example, mobbing is useful and a technique to have in the toolbox, but it isn't something we should use all the time regardless of context.

**Comment by garethbragg** [comment]
I'm not precious about the wording. If this helps people, then I say we go for it ☺️

**Comment by adrianbanks** [comment]
It's probably worth referring to the [definition of adopt](https://www.thoughtworks.com/radar/faq#rings) from Thoughtworks:

> The Adopt ring represents blips that we think you should seriously consider using. We don't say that you should use these for every project; any tool should only be used in an appropriate context. However we do think that a blip in the Adopt ring represents something where there's no doubt that it's proven and mature for use.

**Comment by Dave-Rook** [comment]
More than happy to change either the term or the current definition!

**Comment by nyctef** [comment]
Personally I'd want to stick with Adopt - one of the useful parts of having a tech radar is being opinionated about picking certain technologies/techniques by default, and watering it down to "Available" feels like it would lose that. Of course no tool/technique is perfectly appropriate 100% of the time

**Comment by Dave-Rook** [comment]
Seems like keeping the term adapt but maybe use the Thoughtworks definition?
