### ISSUE TITLE
Code MSIL/IL weaving/injection framework

### ISSUE THREAD

**Issue by fredjeronimo** [red-gate/Tech-Radar#29]
Personal opinion: For me the first question to ask is whether this is even desirable to have at all.

We use [Fody](https://github.com/Fody/Fody) (alongside [Fody.PropertyChanged](https://github.com/Fody/PropertyChanged)) - Endure / Retire

**Comment by fffej** [comment]
Byte weaving magic should be burn with 🔥 in my opinion.

We write code with a focus on simplicity and for me byte weaving is not simple. We've had problems in the past with our own MSIL rewriting for exception handler so I'd be very happy to put this in "Retire".

I don't know how widespread usage of it is though.

**Comment by ChrisLambrou** [comment]
I would suggest killing it with fire, but we did find that internalising some dependencies using ILMerge could be a good solution for making some components more reusable. FWIW, the Usage Client used to ILMerge Newtonsoft.Json until we replaced it with our own json parser (yuk!).

**Comment by garethbragg** [comment]
If we have a thing that we acknowledge we don't want, I'd support it going in _Retire_.

Even if we only have one instance (lookin' at you, RavenDB), I like calling out cruft.

**Comment by fffej** [comment]
In summary, I think this:

Retire:
* Fody 
* IL Weaving (with the description that this isn't merging as @ChrisLambrou points out `ILMerge` can be useful).

Anyone want to make a PR for this?

**Comment by fffej** [comment]
Perhaps @fredjeronimo could make a PR? 😄

**Comment by nyctef** [comment]
I think ideally we'd close the issue [in a PR](https://help.github.com/articles/closing-issues-using-keywords/) which actually adds the decision to the radar

**Comment by allymparker** [comment]
🤦‍♂️ My bad!  Will do!

**Comment by fredjeronimo** [comment]
I'm creating the PR now :)
