### ISSUE TITLE
Javascript Syntax highlighting library

### ISSUE THREAD

**Issue by solar-1992** [red-gate/Tech-Radar#292]
## What change would you like to make to the tech radar?
* Add a library (Investigating prism.js) for doing syntax highlighting in javascript that at least covers PowerShell

## Why do you believe this is valuable to Redgate?
* We intend to display example PowerShell scripts from within SQL Monitor as part of our in-product documentation

## Where should this be on the tech radar?
* Explore - I can't find any similar frameworks anywhere

### If this should be in the _Explore_ ring, who is committed to exploring it?
* I guess the SQL Monitor team to start with

**Comment by Greg-Smulko** [comment]
There is https://github.com/highlightjs/highlight.js that we used for ReadyRoll MsBuild VSTS extension (before rebrand of ReadyRoll and VSTS ;) ).

It's not maintained anymore, but it works pretty well. We also created our own fork for SQL - see https://github.com/red-gate/highlight.js .

Btw, in confluence there is some syntax hightlighting for PowerShell, but unfortunately it doesn't work too well - see [here ](https://documentation.red-gate.com/sql-data-catalog/classification/descope-empty-tables-using-powershell)for an example.

**Comment by solar-1992** [comment]
Does this mean we should use highlight.js or avoid it because it isn't maintained? We are currently using confluence but want to move the example scripts to ship with the product so that we can keep them tied to the customer's version easily

**Comment by Greg-Smulko** [comment]
> Does this mean we should use highlight.js or avoid it because it isn't maintained?

I don't really know. It's a well-established library, so maybe the lack of maintenance is not really such a big problem? But I don't really know if it supports PowerShell at all, we used it for SQL only.
On the other hand, if another library works fine too, and it's maybe easier to consume, thenI'd say just go for it. :)

**Comment by nyctef** [comment]
We're currently using highlight.js too on the Orca team, although I don't think we're particularly attached to it

**Comment by fffej** [comment]
Sounds like highlight.js has enough usage that we should just use that? I'm not so worried about the lack of maintenance cos it's heavily used and at least someone is committing to the repository.

What'd you think @solar-1992 ?

**Comment by solar-1992** [comment]
We can investigate highlight.js (I'll admit we went for prism.js in the meantime but it isn't merged yet)

If we find great issues with highlight what is the right thing to do?

**Comment by Greg-Smulko** [comment]
I'm not sure how good is highlight.js support for PowerShell - there is an [open PR](https://github.com/highlightjs/highlight.js/pull/1386) to improve it.

I'd say that if prism.js works for you guys, then it's such a non-crucial dependency that we can afford to have both highlight.js (as endure?) and prism.js (as adopt?).

**Comment by nyctef** [comment]
Yeah, I don't feel like this is something we need to be super-consistent on - teams adopting one or the other might be fine

**Comment by fffej** [comment]
👍 If highlight.js doesn't do the job on PowerShell, then sounds like reason enough to explore Prism.

**Comment by nyctef** [comment]
Just as a note we've stopped using highlight.js since we're now using [monaco-editor](https://github.com/react-monaco-editor/react-monaco-editor) to display sql, which means we now get an editor + diff viewer for "free".

Monaco is the editor that powers VSCode, and while it adds quite a bit of complexity (it has its own webpack plugin!) it seems to work pretty well.

**Comment by fffej** [comment]
@nyctef Could you make a PR to add monaco?

**Comment by nyctef** [comment]
Yep, will do 👍

**Comment by solar-1992** [comment]
Looks like it might resolve this issue - unless we want to entertain the idea of using two libraries because one is bigger etc with more features and another is smaller for just display

**Comment by nyctef** [comment]
Yeah, I would absolutely not use monaco-editor unless you actually want to use it as an editor - if you're just displaying some sql and want to make it look prettier, then one of the other libraries mentioned in this thread would be much more appropriate.

With that said, I don't think we wanted to specify which highlighting library to use in the radar - they should be pretty much equivalent, anyway? We can probably close this issue at this point.

**Comment by fffej** [comment]
Agreed, I'll close this out (and if anyone disagrees, please feel free to reopen!).
