### ISSUE TITLE
Real :japanese_ogre: Programming Languages

### ISSUE THREAD

**Issue by smobs** [red-gate/Tech-Radar#31]
Explore - F#
Adopt - C#
Endure - Delphi, C++
Retire - VB.Net

**Comment by fffej** [comment]
I think there's a (possible) niche for F# in testing. I love the idea of using [Hedgehog](https://github.com/hedgehogqa/fsharp-hedgehog). Or doing something like [sql-server-gen](https://github.com/fffej/sql-server-gen) but in a more useful language.

**Comment by fffej** [comment]
Doesn't seem there's any dissent here - @smobs could you create a PR for this?

**Comment by fffej** [comment]
(see #50)
