### ISSUE TITLE
SonarQube (especially PR Analysis) requires review

### ISSUE THREAD

**Issue by garethbragg** [red-gate/Tech-Radar#313]
## What change would you like to make to the tech radar?
Honestly I'm not sure yet.

We've used SonarQube to comment on code issues in PRs for a while now. It seems this capability is now only available with [SonarQube Developer edition and above](https://www.sonarsource.com/plans-and-pricing/) (i.e. not the free "Community edition" we use).

This suggests a few possible routes:

* We pony up and pay for a suitable SonarQube edition to keep this system working as it used to
* Roll back to a version of SonarQube that allows our existing workflow
* We strip out the PR analysis infrastructure and find an alternative
* We strip out the PR analysis infrastructure and carry on without it
* Wait until a [third party tool](https://github.com/mc1arke/sonarqube-community-branch-plugin) implements support

I think all options have merit, and there may be more alternatives.

## Why do you believe this is valuable to Redgate?
At the moment we recommend a practice that our teams cannot follow:

> Sonarqube provides automated code review, highlighting quality issues in changing code. **This feedback is best surfaced through automated PR comments.**

(Emphasis added.)

## Where should this be on the tech radar?
TBC, but I'd hope to expedite _Adopt_ being current and correct.

### If this should be in the _Explore_ ring, who is committed to exploring it?
TBC

**Comment by Greg-Smulko** [comment]
Do we know what value the latest version of SonarQube brings us?

If not much, then probably rollback is the simples solution for now, until the third party tool implements support for the Community Edition? 

Also, if we go this path, probably it makes sense to do it ASAP, as I assume that we'd need to restore the SonarQube database from the moment before the upgrade - am I right @nicolasvan ?

**Comment by nicolasvan** [comment]
Whatever we do, let's keep moving forward.... There's no point keeping running a version of sonarqube that is becoming out of date. If we really need PR reviews, we pay for it. (I suspect you would need to make the case for it and convince whoever has the  authority to spend the money that it's worth it though.)

**Comment by fffej** [comment]
https://redgate.slack.com/archives/C070WNDMX/p1586937206079700 contains some opinions:

* Mostly used for PR things
* Dashboard has too many false positives
* SonarLint might be an alternative.
