### ISSUE TITLE
No mention of Entity Framework on the radar

### ISSUE THREAD

**Issue by allymparker** [red-gate/Tech-Radar#316]
So the platform team had a quick chat today about whether we should use an ORM in one of our initial capabilities.  We were debating Dapper vs EF vs ADO.net (FWIW we don't need anything more clever than select *, so we're going to just use ADO.net).  

I wondered what was on the radar - Dapper is in there, but AFAIK there is no mention of EF/EF Core.  Granted EF does more than typical ORMs (migrations for one) - Should we add it?

**Comment by MichelleTaylorRG** [comment]
I mean, we're certainly already using EF (in SQL Data Catalog) whether we should be or not :)

**Comment by matburton** [comment]
> FWIW we don't need anything more clever than select *

Just be careful about injections with that line of thinking 😉

**Comment by fffej** [comment]
It sounds like at a minimum we should capture we're using EF - PR welcome!

I don't know the technology at all - is there a reason to ever choose [NHibernate](https://nhibernate.info/) over EF Core.

It was used in Monitor, but removed years ago (see https://github.com/red-gate/sqlmonitor/pull/543) but there's not much comment on the _why_.

**Comment by matburton** [comment]
Might also be worth clarifying EF vs. EF Core since they're both .NET Core compatible, are fairly different and EF Core is still fairly in flux and not really complete (e.g. `.GroupBy` is getting better but still not there). Not dissing EF Core :wink: just trying to state some facts.

**Comment by fffej** [comment]
Thanks @matburton - hadn't realized that. https://docs.microsoft.com/en-us/ef/efcore-and-ef6/ is a good place to see the differences.

**Comment by fffej** [comment]
There's now some commentary on ORMs in the radar as of #355
