### ISSUE TITLE
Remove techniques quadrant

### ISSUE THREAD

**Issue by fffej** [red-gate/Tech-Radar#339]
## What change would you like to make to the tech radar?

Remove the entire practices quadrant

## Why do you believe this is valuable to Redgate?

We've captured this information on the internal wiki (which gives us more space to add detail).

**Comment by garethbragg** [comment]
We don't have a "practices" quadrant. Which one do you mean?

From the description, I'd guess "Platforms" [as documented on the internal wiki](https://info.red-gate.com/display/PD/Supported+Platforms)?

IIRC the radar renderer depends on four quadrants (as the nae suggests). What could we repalce the removed quadrant with?

**Comment by adrianbanks** [comment]
I think he meant the techniques quadrant.
