### ISSUE TITLE
Scope of Tech-Radar?

### ISSUE THREAD

**Issue by garethbragg** [red-gate/Tech-Radar#39]
A couple of comments have questioned the scope of this techradar. Is it:

* Product-division specific?
* including CoreDev?
* including the webteam?

IF the former, we must consider the other contexts (discussions on [Infrastructure management](https://github.com/red-gate/Tech-Radar/issues/25) and [Supported Browsers](https://github.com/red-gate/Tech-Radar/issues/20) proves this, IMO).

**Comment by tugberkugurlu** [comment]
Related to this, I believe we could do better to make it more clear what each ring means to us and what can go into each. This can make it easy to get us completeness for the v1 of the Radar as we will put constraints on each.

A few ideas on this:

 - https://github.com/red-gate/Tech-Radar/issues/43
 - https://github.com/red-gate/Tech-Radar/issues/44

> Product-division specific?

I believe it would make us move faster on the road of getting to the completion for v1 of the radar if we restrict the radar to Product-division for now as the needs and concerns seem to be very different between product-div and CoreDev.

**Comment by SimonHolness** [comment]
COREDev actively _want_ to align with what's happening in Product teams. So we'll be paying attention to and trying to use the tech radar. From my personal perspective the border between COREDev, Webteam and Product Teams is slightly nebulous and arbitrary - this is all tech development RG's performing and even if management structures and local goals (_for local people_) differ, we're all working for RG and have the same overall goals. 

If you've got good reasons to scope it to the product teams' needs and you're conscious about what you're doing then that seems fine to me, but my gut feeling is that it won't really buy RG anything - it's all RG's code (&systems) and has basically all the same requirements in terms of development and maintenance. 

$0.02 😃

**Comment by fffej** [comment]
@SimonHolness I think that's great, happy to broaden the scope to include  _all_ technology across the business. I'll add a PR to reflect this in the `README.md` file.

@smobs I don't think their tech becomes ours (or at least it's not as simple as that). Early stage R&D is often more about product market fit more than using tech to solve problems.

**Comment by smobs** [comment]
@fffej sorry I should have phrased it as 'in a non ideal world we inherit their codebases'.  
Additionally I believe part of their remit is researching and suggesting technology for prod-div to adopt
