### ISSUE TITLE
Lightweight Architecture Decision Records

### ISSUE THREAD

**Issue by garethbragg** [red-gate/Tech-Radar#40]
I notice [lightweight ADRs](http://thinkrelevance.com/blog/2011/11/15/documenting-architecture-decisions) are in the _Adopt_ section of [Thoughtwork's tech radar](https://www.thoughtworks.com/radar/techniques):

> Much documentation can be replaced with highly readable code and tests. In a world of evolutionary architecture, however, it's important to record certain design decisions for the benefit of future team members as well as for external oversight. Lightweight Architecture Decision Records is a technique for capturing important architectural decisions along with their context and consequences. We recommend storing these details in source control, instead of a wiki or website, as then they can provide a record that remains in sync with the code itself. For most projects, we see no reason why you wouldn't want to use this technique.

This is a practice used by some Redgate teams already.

Should this be in our techradar? If so, where?

I'd suggest in the _Techniques_ quadrant, either in _Adopt_ or _Explore_?

**Comment by tugberkugurlu** [comment]
I would suggest that this should go into Adopt.

We are applying this as a team (/cc @red-gate/spiders). Some examples [here](https://github.com/red-gate/SQLEstateManager-vNext/tree/master/.adr) and [here](https://github.com/red-gate/Mosaic/tree/master/.adr). However, I am not entirely sure we are doing this right based on the discussions we are having around this lately :) 

Most useful bit to me is to be able to go back and refer to the decisions or particular parts of it.

> It would also be interesting to find a mechanism to broadcast the decisions across teams so that we are aware of what other teams are doing but I am probably going off topic.

**Comment by garethbragg** [comment]
PR raised to resolve this. Closing the issue down.
