### ISSUE TITLE
[Techniques] Domain-driven Design

### ISSUE THREAD

**Issue by tugberkugurlu** [red-gate/Tech-Radar#42]
Spiders team have been exploring Domain-driven Design (DDD) in our journey towards stabilizing SQL Data Catalog offering. It's early days for the team to tell about what's working, what's not. There are several reasons to choosing to explore this technique:

 - Keep ourselves honest about striving for [persistence ignorance](https://stackoverflow.com/a/18352064/463785) through proper domain modeling so that we would be able to accommodate foreseen/unforeseen needs around scaling when they make sense to us.
 - We are finding it easy to shape the discussions around business language and structure the codebase around the well-established DDD concepts such as Aggregate, Command, Event, etc. The assumption here is that this will make it easy for us to add/remove/amend functionality due to these battle tested concepts as we are making the intent clear.
 - There is a great deal of resource and community support behind this. [This](http://www.cqrs.nu/faq) even is a good guidance on it's own and [there is an active community behind this](https://github.com/ddd-cqrs-es/slack-community) for support and questions, along side the [Stackoverflow knowledge](https://stackoverflow.com/questions/tagged/domain-driven-design) which got built-up over time and [all the other resources](https://github.com/heynickc/awesome-ddd).

I propose that we put this under *Explore* ring for *Techniques* quadrant. 

> side note: I also believe there should be accountability associated with exploring a quadrant. There should be a point that the team should make it visible to the rest of the company what the results of the exploration was and what the recommendation is (e.g. take it to Adopt, make a case for more knowledge investment, stop exploring and endure/retire, etc.).

**Comment by tugberkugurlu** [comment]
@chenchen1987 anything else you want to add?

**Comment by chenchen1987** [comment]
@tugberkugurlu  well summed up. Nothing to add here

**Comment by fffej** [comment]
@tugberkugurlu Really happy with exploring DDD. Do you want to make a PR and I'll merge?

In terms of accountability - once we've got v1 of the Radar out I'm going to suggest we review it on a regular cadence (3 months? 6 months?). I hope the accountability will come by you providing an update at that point about what you've learnt about DDD, why it works (or why it doesn't) together with a recommendation of where to go next?
