### ISSUE TITLE
Should Adopt ring require previous success?

### ISSUE THREAD

**Issue by tugberkugurlu** [red-gate/Tech-Radar#44]
A few of the suggestions are proposing to put some items under Adopt and some of them have no trial or previous success associated to them in context of our product teams (as far as I am aware of, I could be wrong). #35 is a good example to this. Even if the approach is a very successful one and has been battle tested for years, we have no experience of using this for our products. Therefore, I don't think it would be healthy for us to put items under Adopt ring if they don't have any previous success attached to them in context of our product teams' experiences.

I propose that we restrict Adopt to only items which we have tried before and show strong sings of success.

There are a few outcomes I expect us to achieve through this change:

 - Make it more clear what Adopt ring means to us.
 - As a result of above, we should be able to make decisions faster on what should go into here.

**Comment by nyctef** [comment]
> Therefore, I don't think it would be healthy for us to put items under Adopt ring if they don't have any previous success attached to them in context of our product teams' experiences.

In general I think this is a good principle and I agree with it, but I think we might want to make a specific exception for dogfooding our own products - because we gain extra value from battle-testing our own products and learning about their limitations.

**Comment by tugberkugurlu** [comment]
> because we gain extra value from battle-testing our own products and learning about their limitations.

true but I would still want to derisk the situation by letting one team to explore it first and then reporting back to recommend where to take it.

**Comment by garethbragg** [comment]
For v1 of the tech radar, I'd much prefer we record the reality of where we are. That, in my mind, means anything in _Adopt_ must be successfully in-use with at least one Redgate team.

Yes, dogfooding our product would be good. But we don't do it already. We need to _explore_ where our products can be effectively dogfood-ed and see how successfully we can do it before the practice can be successfully _adopted_.

Yes, I chose those italic words carefully.
