### ISSUE TITLE
What are the rings?

### ISSUE THREAD

**Issue by fffej** [red-gate/Tech-Radar#5]
Thoughtworks Radar has four rings, which we'll describe starting from the middle:

* The *Adopt* ring represents blips that we think you should be using now. We don't say that you should use these for every project; any tool should only be used in an appropriate context. However we do think that a blip in the Adopt ring represents something where there's no doubt that it's proven and mature for use.
* The *Trial* ring is for blips that we think are ready for use, but not as completely proven as those in the Adopt ring. So for most organizations we think you should use these on a trial basis, to decide whether they should be part of your toolkit. Typically we're happy to use trial blips now, but we realize that most readers will be more cautious than us.
* The *Assess* ring are things that you should look at closely, but not necessarily trial yet - unless you think they would be a particularly good fit for you. Typically, blips in the Assess ring are things that we're currently trialing, on our projects.
* The *Hold* ring is for things that are getting attention in the industry, but we don't think are ready for use. Sometimes this is because we don't think they're mature enough yet: sometimes it means we think they're irredeemably flawed. We don't have an "avoid" ring, but we do throw things in the Hold ring that we wish our clients wouldn't use.

I think our needs are somewhat different in the context of the New Tech Moratorium.

For example, some tech it's important for us to standardize on (perhaps even across all products) and some tech we want to actually get rid of because it's a pain to maintain that software. I don't think the Thoughtworks rings adequately describe this.

**Comment by garethbragg** [comment]
I agree it lacks a degree of finesse, but I'm not convinced the value we'd get from defining our own rings would be all that great. (NB: I'm also not actively against it.)

For the categories you suggest, I wouldn't be hugely uncomfortable putting that kind of stuff in _Trial_. If Dan's comments are fair, I would expect that section to get quite bloated to highlight the problem!

**Comment by fffej** [comment]
Here's my stab at what the rings could be to work for Redgate after talking with @garethbragg 

* The _Adopt_ ring represents technology Redgate has agreed to standardize on. This forms our default Tech Stack - everything in here is a solid choice and aligns with the rest of the teams. An example of this would be C#.

* The _Hold_ ring represents technology we currently use and haven't yet agreed a common one. Examples of this might be all the logging frameworks we use across our tools - we haven't agreed the "one true way" of logging (or even whether that's worth doing).

* The _Trial_ ring represents technology we are trialing but we aren't standardizing on. An example of this would be Electron - we're using it in a single product but until we've shipped to more users and got more confident I think it remains in this ring. New blips in this ring represent technology we're interested in, but aren't doing anything about yet - for example, Kubernetes.

* The _Kill_ ring represents technology that's served it's purpose for Redgate, but now we've chosen to get rid of. For example, maybe old versions of ASP.NET should be phased out in favour of ASP.NET Core? Each item in the _Kill_ ring should have a corresponding thing in adopt.

**Comment by tugberkugurlu** [comment]
I believe the default rings make sense to me, it's a useful indicator to a team who are exploring ways to get a particular job but not sure whether it's being adopted at Redgate already. However, we may provide a bit more relevant context for these. Probably matches the descriptions you have on https://github.com/red-gate/Tech-Radar/issues/5#issue-373999784 but I will put them here anyway just to emphasize.

## Adopt

These are the tools, patterns and practices, platforms, etc. that we have been using for a while and it just works ™️. If you are looking for a get a job done quickly and any of the stuff under here solves your problem, go with it and save some cognitive space for your team. If you go with any item under "Adopt", you will more likely to get help from teams at Redgate who adopt that and it's very likely that they have battle scars on this.

## Trial

These are the tools, patterns and practices, platforms, etc. solves a particular problem to get a job done which none of the ones under "Adopt" is able to pull off, or the ones under "Hold" is not being effective to on getting the job done. It's likely that small amount of teams are trying these and they haven't seen the results they should to put these into either "Adopt" or "Hold".

## Assess

Has the same context as "Trial" but haven't committed to give it a go yet. This stage is usually around assessing the trade-offs. Once the assessment ends, we may end up getting rid of this item or promote it to Trial. If the evidence is compelling that this is an absolute rubbish choice, it may demoted to "Hold" but very unlikely to happen as it will mostly be opinion based.

## Hold

We either adopted or tried these and they just don't work ™️. Unless you have absolute legitimate reasons that this is the tool, pattern, platform, etc. for the job, trust the people who went through hell with these and don't even think about adopting or even trying. If you are a team who is using this tool, pattern, platform, etc., you either try to find a replacement, or if the cost benefit analysis doesn't seem to have a sensible result, try not to put more complexity over this.

**Comment by smobs** [comment]
I wonder about something like:

## Adopt

This what you should be using to solve X problem.

## Explore

This has potential, and is worth experimenting with in 10% time/running a trial on your team.

## Endure

This is no longer how we do things, it is ok this to be used, but don't add more and migrate off were possible.

## Retire
If you use this and are not actively spending time migrating away then Jeff will punish you.

**Comment by smobs** [comment]
I see it as a WIP kanban style affair:
Explore -> Adopt -> Endure -> Retire.

Explore finds us things worth moving to.  
To adopt we need to move whatever is currently in adopt to Endure.  So tech we are already enduring needs to be retired by migrating to the newly adopted option.

**Comment by tugberkugurlu** [comment]
@smobs great new perspective, I liked the "Retire" suggestion a lot.

> ## Explore
> This has potential, and is worth experimenting with in 10% time/running a trial on your team.

I see this as actual commitment, rather than being vague "hey looks good, wanna try" type of one. The diff between Adopt and this would be your confidence level on how likely you would recommend this to another team to use because you haven't seen the expected outcome yet and there is still time to analyze it.

**Comment by smobs** [comment]
> I see this as actual commitment, rather than being vague "hey looks good, wanna try" type of one. The diff between Adopt and this would be your confidence level on how likely you would recommend this to another team to use because you haven't seen the expected outcome yet and there is still time to analyze it.

👍  
## Explore 
1 team is trialing this.  They will either pitch it as something to adopt, or back it out of their codebase: it doesn't get to hang around.

**Comment by ChrisHurley** [comment]
👍 to Adopt/Explore/Endure/Retire. I think that Trial/Assess on the ThoughtWorks one sound too similar unless you have a clear process by which things move between them.

I guess the question is, if I see something in Explore (or Trial/Assess), should I pull it in and start using it to see how it goes if it seems it might solve some problem for me, or should I wait until it hits Adopt? What's the process by which it does that? That needs to be fairly clear if we're using this as a directive about how we develop.

**Comment by fffej** [comment]
👍 to Adopt/Explore/Endure/Retire from me as well.

@ChrisHurley makes a good point about defining stuff in Explore; when should it be used and when should it not?

Maybe we should start simply and just label which team is doing work in the Explore phase and ask for a conversation to happen before pulling it in? Or we could do an [RFC style](https://blog.pragmaticengineer.com/scaling-engineering-teams-via-writing-things-down-rfcs/) process for adopting new technology?
