### ISSUE TITLE
[Tool] Tools for Architecture Diagrams

### ISSUE THREAD

**Issue by chenchen1987** [red-gate/Tech-Radar#69]
The Spiders team have been exploring ways to make ever green architectural diagrams of the data catalog. As a result, [Lucidchart](https://www.lucidchart.com) has been put on the table.

### Why is maintaining an ever green architectural diagram important

- Per description in #42, the team is investing time effort into adopting DDD pattern into SQL Data Catalog, one of the foreseen difficulties that we need to overcome is adopting its Ubiquitous language
- DDD is something the team hasn't had previous experience with in the past
- There is a strong emphasis on carefully designing the domain layer, namely the aggregate's consistency boundaries

The belief is that having visualised architectural diagrams would relief us the above pains we will be experiencing.

### Benefits of using Lucidchart

Some of the functionalities we could take advantages of:

- Individuals in the team are able to create/edit the diagrams, which can be shared across the team
- Make responsive comments on individual components on the diagrams for better communication
- Ability to zoom into lower level architectural diagrams, by adding hot spots on particular components on the higher level ones

**Comment by fffej** [comment]
Excellent - I guess @fredjeronimo might chime in here with whatever tool the Prompt team used to produce the [C4 diagrams](https://c4model.com/) for Prompt?

**Comment by adrianbanks** [comment]
There's also [Strucurizr](https://structurizr.com) (made by Simon Brown who came up with the C4 model) which enables you to create architecture diagrams from code with some hope of keeping them up to date more easily.

**Comment by nyctef** [comment]
I think in an ideal solution, the source of truth for the diagrams would be source-controlled next to the relevant code so we have a chance of enforcing that they change together.

I don't know if lucidchart lets us do something like that - it might just need to export PNGs out to the repo (which can be replaced with PNGs from another tool if necessary). The code definitions from Structurizr look promising, but the syntax isn't the simplest thing in the world - it's not too complicated but it might turn off people from editing diagrams.

I think an ideal solution would look something a bit like https://www.websequencediagrams.com/ , but for any diagram type :/

**Comment by fredjeronimo** [comment]
We are currently using [draw.io](https://www.draw.io/) for generating our [C4 models](https://info.red-gate.com/display/SP/Prompt%27s+architecture) in Prompt. This was mostly picked as an easy to use and setup solution for what is mostly at present a digital representation of a low tech (post-its and whiteboard) team brainstorm exercise from our new [mob architecture](https://info.red-gate.com/display/SP/Outcome+of+mob+architecture+sessions) sessions (we only just started the process this week).

To be perfectly honest, I'm not too worried about which tool we end up picking to achieve architectural diagrams (as long as we can create custom shapes and it's low maintenance) as I'm more concerned about integrations with other environments, most notably Confluence. At my previous job, we used [Gliffy](https://www.gliffy.com/) and one of its main attractives is that it had a [Confluence plugin](https://marketplace.atlassian.com/apps/254/gliffy-diagram-for-confluence?hosting=cloud&tab=overview) that hooked directly in the webpages. Each diagram had a full history and you could even edit them separately from the page contents themselves.

**Comment by fffej** [comment]
I'd like to make sure the Radar captures the status quo and things we are trialling now (or will commit to) and things we should adopt.

Seems that in _Explore_ we've got both draw.io and LucidChart. These both look like drawing tools (rather than architecture <-> code things). @fredjeronimo and @chenchen1987 Do you think we can get opinionated enough to choose one now?

@adrianbanks and @nyctef have highlighted some code -> diagram tools. Are these interesting enough to commit to exploring, or something of interest for some future time?

**Comment by chenchen1987** [comment]
Speaking on behalf of the spiders team, we are opinionated enough to choose one now yet. And I've personally not explored extensively of the other tools mentioned in this thread.

**Comment by fffej** [comment]
In that case, I'd suggest

Explore
- draw.io (and some reasons why)
- LucidChart (and some reasons why)

Next iteration we'll try to understand the pros/cons of both and make a decision about whether converging on a single tool is a good thing (or not!).

Anyone fancy making a PR? 🙏

**Comment by tugberkugurlu** [comment]
> There's also [Strucurizr](https://structurizr.com) (made by Simon Brown who came up with the C4 model) which enables you to create architecture diagrams from code with some hope of keeping them up to date more easily.

I have tried this several times but I find this very lacking to express the thoughts and collaborate on these. Lucidchart seems to tick all the collabration boxes for us, for example. We looked whether Visio was on OneDrive but it doesn't seem to be there and Lucidchart seemed to be the closest to having Visio on OneDrive :)

**Comment by fredjeronimo** [comment]
I'm happy to trial out any for our work in Prompt (happy to discuss with other teams -- perhaps a joint test session might be worthwhile to conduct?). My only true request is that we package a Confluence plugin with whatever choice we pick in the end. Like Gliffy, it seems both draw.io ([here](https://marketplace.atlassian.com/apps/1210933/draw-io-diagrams-for-confluence?hosting=cloud&tab=overview)) and LucidChart ([here](https://www.lucidchart.com/pages/integrations/confluence)) have at least one integration with Confluence (more may exist).
