### ISSUE TITLE
JS Utility libraries

### ISSUE THREAD

**Issue by allymparker** [red-gate/Tech-Radar#90]
I'm trying to avoid this becoming a copy paste of packages.json,  but I feel like there are some common choices we need to make around JS utility libs that would make life easier moving from team to team.  Thoughts?

Adopt:
- lodash (enumerable functions)
- moment (Date formatting)
- numeral (number formatting)
- highcharts (charting library)

Endure
- underscore (enumerable functions)

**Comment by deneboulton** [comment]
`moment` is the obvious lib of choice for dates, however I would like to make you aware of [day.js](https://github.com/iamkun/dayjs) - recently replaced a usage of moment for this where we are formatting dates.

**Comment by allymparker** [comment]
Interesting.  What's the benefit of using day vs moment?

**Comment by deneboulton** [comment]
For us it pretty much came down to the size of the lib since ours is a hosted app - and one where that content is not gzipped [ATM].

**Comment by garethbragg** [comment]
Would it be fair to put `day.js` in _Explore_, based on what CoreDev are doing?

**Comment by ChrisHurley** [comment]
We use `underscore` (preferring ES6, but some things are missing) but I have no problem with `lodash`.

Otherwise, our non-view-related libraries are:
- [js-cookie](https://github.com/js-cookie/js-cookie)
- [whatwg-fetch](https://github.com/github/fetch)

**Comment by deneboulton** [comment]
We currently use [Axios](https://github.com/axios/axios) due to having to support IE 9/10 up to about 6 months ago; now we no longer have to support those browser versions I believe we could happy use `whatwg-fetch` and `js-cookie`.

**Comment by fffej** [comment]
This ones been open for a while. @allymparker could you have a go at summarizing and creating a PR?

**Comment by allymparker** [comment]
Having talked with @fffej I think what we're going to do is have a second tech radar in this repo for these smaller libraries because:

* It'll stop the main radar getting noisy.  The main radar will be a top level stack ie React/Redux
* Currently it's hard to know what libraries are being used through out the building and why that particular one or not.  This ends up with wasted effort learning, investigating and choosing libraries
* It'll provide a place for both Nuget and NPM packages

I'll create a PR...
