### ISSUE TITLE
GUI tests framework for Win apps

### ISSUE THREAD

**Issue by Greg-Smulko** [red-gate/Tech-Radar#99]
It seems we use multiple different frameworks for GUI tests:
- SCA uses [Windows Application Driver](https://github.com/Microsoft/WinAppDriver)
- SoC uses Ranorex
- The Toolbelt Team uses Coded UI

**Comment by garethbragg** [comment]
Ranorex was in _Retire_ on a prior tech radar (and was mostly retired).  It certainly shouldn't be adopted any wider.

My gut says it should be in _Retire_ now, too.

**Comment by nyctef** [comment]
IIRC the Compare GUI tests are built with `UIAutomation`/`System.Windows.Automation` which is one of the underlying frameworks that Ranorex/Coded UI abstracts away. It's the proper accessibility framework for WPF so it works quite well assuming you're writing a WPF application :)
